src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity('email', 'This email already existe!')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\Column(type: Types::STRING, length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Email()]
    private ?string $email = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $lastname = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(type: Types::JSON)]
    #[Assert\NotBlank()]
    private array $roles = ['ROLE_USER'];

    private ?string $plainPassword = null;

    #[ORM\Column(type: Types::STRING, length: 255)]
    private ?string $password = null;

    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private string $reset_token;

    #[ORM\Column(type: Types::BOOLEAN)]
    private bool $is_verified = false;

    /** @var ArrayCollection<int, Post> */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Post::class, cascade: ['remove'], orphanRemoval: true)]
    private Collection $posts;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER'; // ROLE_USER minimum by default

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function eraseCredentials(): void
    {
        $this->plainPassword = null;
    }

    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return (string) $this->email;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('lastname', TextType::class, [
            'label' => 'Lastname',
            'constraints' => [
                new NotBlank(),
                new Length([
                    'min' => 2,
                ]),
            ],
        ])
        ->add('firstname', TextType::class, [
            'label' => 'Firstname',
            'constraints' => [
                new NotBlank(),
                new Length([
                    'min' => 2,
                ]),
            ],
        ])
        ->add('email', EmailType::class, [
            'constraints' => [
                new NotBlank(),
            ],
        ])
        ->add('password', PasswordType::class, [
            'mapped' => false,
            'required' => false,
            'label' => 'Password',
            'attr' => [
                'type' => 'password',
            ],
            'constraints' => [
                new Length([
                    'min' => 6,
                ]),
            ],
        ])
        ->add('roles', ChoiceType::class, [
            'choices' => [
                'USER' => 'ROLE_USER',
                'ADMIN' => 'ROLE_ADMIN',
            ],
            'multiple' => true,
        ])
        ->add('is_verified', ChoiceType::class, [
            'choices' => [
                'Yes' => true,
                'No' => false,
            ],
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/user')]
#[IsGranted('ROLE_ADMIN')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app.user.index', methods: ['GET'])]
    public function index(UserRepository $userRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $pagination = $paginator->paginate(
            /* @phpstan-ignore-next-line */
            $userRepository->getAllUsersQuery(), /* query NOT result */
            $request->query->getInt('page', 1), /* page number */
            8 /* limit per page */
        );

        return $this->render('user/index.html.twig', [
            'users' => $pagination,
        ]);
    }

    #[Route('/new', name: 'app.user.new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (!is_null($form->get('password')->getData())) {
                $user->setPassword(
                    $userPasswordHasher->hashPassword(
                        $user,
                        $form->get('password')->getData()
                    )
                );
                $userRepository->save($user, true);

                return $this->redirectToRoute('app.user.index', [], Response::HTTP_SEE_OTHER);
            } else {
                $form->get('password')->addError(new FormError('Password is required'));
            }
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app.user.show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app.user.edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (!is_null($form->get('password')->getData())) {
                $user->setPassword(
                    $userPasswordHasher->hashPassword(
                        $user,
                        $form->get('password')->getData()
                    )
                );
            }
            $userRepository->save($user, true);

            return $this->redirectToRoute('app.user.index', [], Response::HTTP_SEE_OTHER);
        }
        // dd($user->getId()->toBinary(), $form);
        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app.user.delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid((string) 'delete'.$user->getId(), (string) $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app.user.index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app.user.delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
<div class="row">
    {{ form_start(form, {'attr': {'id': 'form-post', 'class': 'row' }}) }}
    <div class="col-12 col-md-8">
        {{ form_widget(form._token) }}
        <div class="mb-3">
            {{ form_label(form.lastname, 'Lastname', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.lastname, { 'attr': {'class': 'form-control'} }) }}
            {% if form_errors(form.lastname) %}
            <div id="post_lastnameFeedback" class="invalid-feedback">
                {{ form_errors(form.lastname) }}
            </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form_label(form.firstname, 'Firstname', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.firstname, { 'attr': {'class': 'form-control'} }) }}
            {% if form_errors(form.firstname) %}
            <div id="post_firstnameFeedback" class="invalid-feedback">
                {{ form_errors(form.firstname) }}
            </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form_label(form.email, 'Email', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.email, { 'attr': {'class': 'form-control'} }) }}
            {% if form_errors(form.email) %}
            <div id="post_emailFeedback" class="invalid-feedback">
                {{ form_errors(form.email) }}
            </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form_label(form.password, 'Password', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.password, { 'attr': {'class': 'form-control'} }) }}
            {% if form_errors(form.password) %}
            <div id="post_passwordFeedback" class="invalid-feedback">
                {{ form_errors(form.password) }}
            </div>
            {% endif %}
        </div>
    </div>
    <div class="col-12 col-md-4 d-flex flex-column">
        <div class="order-1 order-md-0">
            <p class="mb-0 fw-bold">Actions</p>
            <hr class="my-4">
            <div class="mb-3">
                {% set btn_label = button_label|default('Save') %}
                <button type="submit" id="submit-post" class="btn btn-success btn-lg w-100">{{ btn_label
                    }}</button>
            </div>
        </div>
        <div class="order-0 order-md-1">
            <div class="mb-3">
                <hr class="my-4 d-none d-md-block">
                {{ form_label(form.roles, 'Roles', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.roles, { 'attr': {'class': 'form-control'} }) }}
                {% if form_errors(form.roles) %}
                <div id="post_rolesFeedback" class="invalid-feedback">
                    {{ form_errors(form.roles) }}
                </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form_label(form.is_verified, 'Active', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.is_verified, { 'attr': {'class': 'form-control'} }) }}
                {% if form_errors(form.is_verified) %}
                <div id="post_is_verifiedFeedback" class="invalid-feedback">
                    {{ form_errors(form.is_verified) }}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
{{ form_end(form, {'render_rest': false}) }}
</div>

templates/user/edit.html.twig
{% extends 'base.html.twig' %}
{% set referer = app.request.headers.get('referer')|default('/post/') %}
{% block title %}Edit User{% endblock %}

{% block body %}
<div class="row">
    <div class="col-12 col-md-8">
        <h1 class="mt-3">Edit User </h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ path('app.home') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ path('app.user.index') }}">All users</a></li>
            <li class="breadcrumb-item active">Edit user</li>
        </ol>
    </div>
    <div class="col-12 col-md-4">
        <div class="d-flex h-100 align-items-center justify-content-start justify-content-md-end">
            <a href="{{ path('app.user.new') }}" class="btn btn-primary me-1">
                Create new
            </a>
            <a href="{{ referer }}" class="btn btn-light border border-secondary">
                <i class="fa-solid fa-chevron-left"></i>
                Back
            </a>
        </div>
    </div>
    <div class="col-12">
        {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}
    </div>
</div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Users{% endblock %}

{% block body %}
<div class="row">
    <div class="col-12 col-md-10">
        <h1 class="mt-3">All users</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ path('app.home') }}">Dashboard</a></li>
            <li class="breadcrumb-item active">All users</li>
        </ol>
    </div>
    <div class="col-12 col-md-2">
        <div class="d-flex h-100 align-items-center justify-content-start justify-content-md-end">
            <a href="{{ path('app.user.new') }}" class="btn btn-primary">Create new</a>
        </div>
    </div>
    <div class="col-12 h-full">
        <hr class="my-2">
        <div class="table-responsive">
            <table class="table table-hover align-middle">
                <thead>
            <tr>
                <th>Lastname</th>
                <th>Firstname</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Activated</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td class="d-none d-md-table-cell">{{ user.lastname }}</td>
                <td class="d-none d-md-table-cell">{{ user.firstname }}</td>
                <td scope="row">{{ user.email }}</td>
                <td class="d-none d-md-table-cell">
                    {# {{ user.roles ? user.roles|json_encode : '' }} #}
                    {% for role in user.roles %}
                        <span class="badge bg-secondary">{{ role[5:] }}</span>
                    {% endfor %} 
                </td>
                <td class="d-none d-md-table-cell">
                    {{ user.isVerified ? '<span class="badge bg-success">Yes</span>' : '<span class="badge bg-danger">No</span>' }}
                </td>
                <td class="d-none d-md-table-cell">{{ user.createdAt ? user.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td class="d-none d-md-table-cell">{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td class="d-none d-md-table-cell">
                    <div class="d-flex justify-content-end">
                        <a href="{{ path('app.user.show', {'id': user.id}) }}" class="btn btn-success me-1">
                            <i class="fa-regular fa-eye"></i>
                            Show
                        </a>
                        <a href="{{ path('app.user.edit', {'id': user.id}) }}" class="btn btn-primary me-1">
                            <i class="fa-regular fa-pen-to-square"></i>
                            Edit
                        </a>
                        <form method="post" action="{{ path('app.user.delete', {'id': user.id}) }}"
                            onsubmit="return confirm('Are you sure you want to delete this item?');">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
                            <button class="btn btn-danger">
                                <i class="fa-solid fa-trash"></i>
                                Delete
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
        {% include 'partials/pagination.html.twig' with {'pagination': users, align: 'right'} %}
    </div>
</div>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
<div class="row">
    <div class="col-12 col-md-8"> 
        <h1 class="mt-3">Create User</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ path('app.home') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ path('app.user.index') }}">All users</a></li>
            <li class="breadcrumb-item active">Create user</li>
        </ol>
    </div>
    <div class="col-12 col-md-4">
        <div class="d-flex h-100 align-items-center justify-content-start justify-content-md-end">
            <a href="{{ path('app.user.index') }}" class="btn btn-light border border-secondary">
                <i class="fa-solid fa-chevron-left"></i>
                Back
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <hr class="my-4">
    </div>
</div>
{{ include('user/_form.html.twig') }}
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
<div class="row">
    <div class="col-12 col-md-8">
        <h1 class="mt-3">User</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ path('app.home') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{ path('app.user.index') }}">All users</a></li>
        </ol>
    </div>
    <div class="col-12 col-md-4">
        <div class="d-flex h-100 align-items-center justify-content-start justify-content-md-end mb-4">
            {% if(app.user.email == user.email) or (is_granted('ROLE_ADMIN')) %}
            <a href="{{ path('app.user.edit', {'id': user.id}) }}" class="btn btn-primary mx-1">
                <i class="fa-regular fa-pen-to-square"></i>
                Edit
            </a>
            <form method="post" action="{{ path('app.user.delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
                <button class="btn btn-danger">
                    <i class="fa-solid fa-trash"></i>
                    Delete
                </button>
            </form>
            {% endif %}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <hr class="my-4">
    </div>
</div>
<div class="row">
    <div class="col-12">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <th>Lastname</th>
                    <td>{{ user.lastname }}</td>
                </tr>
                <tr>
                    <th>Firstname</th>
                    <td>{{ user.firstname }}</td>
                </tr>
                <tr>
                    <th>Id</th>
                    <td>{{ user.id }}</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>{{ user.email }}</td>
                </tr>
                <tr>
                    <th>Roles</th>
                    <td>
                        {% for role in user.roles %}
                            <span class="badge bg-secondary">{{ role[5:] }}</span>
                        {% endfor %}                    
                    </td>
                </tr>
                <tr>
                    <th>Active</th>
                    <td>{{ user.isVerified ? '<span class="badge bg-success">Yes</span>' : '<span class="badge bg-danger">No</span>' }}</td>
                </tr>
                <tr>
                    <th>CreatedAt</th>
                    <td>{{ user.createdAt ? user.createdAt|date('d-m-Y H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>UpdatedAt</th>
                    <td>{{ user.updatedAt ? user.updatedAt|date('d-m-Y H:i:s') : '' }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}